In [78]:
import pandas as pd
import matplotlib.pyplot as plt

In [79]:
df = pd.read_csv("../data/raw/matches.csv")
df.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [80]:
print(f"Raw data shape: {df.shape}")
print(f"Columns: {df.columns}")
print(f"Misisng values: \n{df.isnull().sum()}")

Raw data shape: (1248, 37)
Columns: Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed',
       'replay', 'match_date', 'match_time', 'stadium_id', 'stadium_name',
       'city_name', 'country_name', 'home_team_id', 'home_team_name',
       'home_team_code', 'away_team_id', 'away_team_name', 'away_team_code',
       'score', 'home_team_score', 'away_team_score', 'home_team_score_margin',
       'away_team_score_margin', 'extra_time', 'penalty_shootout',
       'score_penalties', 'home_team_score_penalties',
       'away_team_score_penalties', 'result', 'home_team_win', 'away_team_win',
       'draw'],
      dtype='object')
Misisng values:
key_id                       0
tournament_id                0
tournament_name              0
match_id                     0
match_name                   0
stage_name                   0
group_name                   0
group_stage                  0
knockout_stage               0
replayed                     0
replay                       0
match_date                   0
match_time                   0
stadium_id                   0
stadium_name                 0
city_name                    0
country_name                 0
home_team_id                 0
home_team_name               0
home_team_code               0
away_team_id                 0
away_team_name               0
away_team_code               0
score                        0
home_team_score              0
away_team_score              0
home_team_score_margin       0
away_team_score_margin       0
extra_time                   0
penalty_shootout             0
score_penalties              0
home_team_score_penalties    0
away_team_score_penalties    0
result                       0
home_team_win                0
away_team_win                0
draw                         0
dtype: int64

In [81]:
# The card system was introduced in 1970; there was no such system prior to that, so we drop the previous tournaments

df["match_date"] = pd.to_datetime(df["match_date"])
df = df[df["match_date"].dt.year >= 1970]

# This work focuses on FIFA Men's World Cup only
df = df[df["tournament_name"].str.contains("Men's")]

print(f"Current data shape: {df.shape}")
df.head()

Current data shape: (764, 37)

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
200,201,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,group stage,Group 1,1,0,0,...,0,0,0,0-0,0,0,draw,0,0,1
201,202,WC-1970,1970 FIFA Men's World Cup,M-1970-02,Uruguay vs Israel,group stage,Group 2,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
202,203,WC-1970,1970 FIFA Men's World Cup,M-1970-03,England vs Romania,group stage,Group 3,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
203,204,WC-1970,1970 FIFA Men's World Cup,M-1970-04,Peru vs Bulgaria,group stage,Group 4,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
204,205,WC-1970,1970 FIFA Men's World Cup,M-1970-05,Belgium vs El Salvador,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0

In [82]:
# drop unused/irrelevant columns

df = df.drop(columns = ["key_id", "group_name", "match_time", "replay", "replayed", "country_name", "stadium_id", "stadium_name", "city_name",
                        "group_stage", "knockout_stage", "home_team_code", "away_team_code", "home_team_score_margin", 
                        "away_team_score_margin", "score_penalties"]).reset_index().drop(columns = "index")
print(f"Current data shape: {df.shape} \n")
print(f"Columns: {df.columns} \n")
df.head()

Current data shape: (764, 21)

Columns: Index(['tournament_id', 'tournament_name', 'match_id', 'match_name',
       'stage_name', 'match_date', 'home_team_id', 'home_team_name',
       'away_team_id', 'away_team_name', 'score', 'home_team_score',
       'away_team_score', 'extra_time', 'penalty_shootout',
       'home_team_score_penalties', 'away_team_score_penalties', 'result',
       'home_team_win', 'away_team_win', 'draw'],
      dtype='object')

,tournament_id,tournament_name,match_id,match_name,stage_name,match_date,home_team_id,home_team_name,away_team_id,away_team_name,...,home_team_score,away_team_score,extra_time,penalty_shootout,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,group stage,1970-05-31,T-46,Mexico,T-72,Soviet Union,...,0,0,0,0,0,0,draw,0,0,1
1,WC-1970,1970 FIFA Men's World Cup,M-1970-02,Uruguay vs Israel,group stage,1970-06-02,T-84,Uruguay,T-40,Israel,...,2,0,0,0,0,0,home team win,1,0,0
2,WC-1970,1970 FIFA Men's World Cup,M-1970-03,England vs Romania,group stage,1970-06-02,T-28,England,T-61,Romania,...,1,0,0,0,0,0,home team win,1,0,0
3,WC-1970,1970 FIFA Men's World Cup,M-1970-04,Peru vs Bulgaria,group stage,1970-06-02,T-56,Peru,T-10,Bulgaria,...,3,2,0,0,0,0,home team win,1,0,0
4,WC-1970,1970 FIFA Men's World Cup,M-1970-05,Belgium vs El Salvador,group stage,1970-06-03,T-06,Belgium,T-27,El Salvador,...,3,0,0,0,0,0,home team win,1,0,0

In [83]:
df1 = pd.read_csv("/Users/khuenguyen/Desktop/the-12th-man/data/raw/teams.csv")
df1.head()

,key_id,team_id,team_name,team_code,mens_team,womens_team,federation_name,region_name,confederation_id,confederation_name,confederation_code,mens_team_wikipedia_link,womens_team_wikipedia_link,federation_wikipedia_link
0,1,T-01,Algeria,DZA,1,0,Algerian Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Algeria_national...,not applicable,https://en.wikipedia.org/wiki/Algerian_Footbal...
1,2,T-02,Angola,AGO,1,0,Angolan Football Federation,Africa,CF-2,Confederation of African Football,CAF,https://en.wikipedia.org/wiki/Angola_national_...,not applicable,https://en.wikipedia.org/wiki/Angolan_Football...
2,3,T-03,Argentina,ARG,1,1,Argentine Football Association,South America,CF-4,South American Football Confederation,CONMEBOL,https://en.wikipedia.org/wiki/Argentina_nation...,https://en.wikipedia.org/wiki/Argentina_women'...,https://en.wikipedia.org/wiki/Argentine_Footba...
3,4,T-04,Australia,AUS,1,1,Football Australia,Oceania,CF-1,Asian Football Confederation,AFC,https://en.wikipedia.org/wiki/Australia_men%27...,https://en.wikipedia.org/wiki/Australia_women'...,https://en.wikipedia.org/wiki/Football_Australia
4,5,T-05,Austria,AUT,1,0,Austrian Football Association,Europe,CF-6,Union of European Football Associations,UEFA,https://en.wikipedia.org/wiki/Austria_national...,not applicable,https://en.wikipedia.org/wiki/Austrian_Footbal...

In [84]:
df1 = df1[["team_id", "confederation_code"]]
df1

   team_id confederation_code
0     T-01                CAF
1     T-02                CAF
2     T-03           CONMEBOL
3     T-04                AFC
4     T-05               UEFA
..     ...                ...
83    T-84           CONMEBOL
84    T-85               UEFA
85    T-86               UEFA
86    T-87               UEFA
87    T-88                CAF

[88 rows x 2 columns]

In [85]:
df = df.merge(df1.rename(columns = {"team_id": "home_team_id"}), 
              on = "home_team_id", 
              how = "left").rename(columns = {"confederation_code": "home_team_confederation"})

df = df.merge(df1.rename(columns = {"team_id": "away_team_id"}), 
              on = "away_team_id", 
              how = "left").rename(columns = {"confederation_code": "home_team_confederation"})

In [86]:
df

,tournament_id,tournament_name,match_id,match_name,stage_name,match_date,home_team_id,home_team_name,away_team_id,away_team_name,...,extra_time,penalty_shootout,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw,home_team_confederation,home_team_confederation
0,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,group stage,1970-05-31,T-46,Mexico,T-72,Soviet Union,...,0,0,0,0,draw,0,0,1,CONCACAF,UEFA
1,WC-1970,1970 FIFA Men's World Cup,M-1970-02,Uruguay vs Israel,group stage,1970-06-02,T-84,Uruguay,T-40,Israel,...,0,0,0,0,home team win,1,0,0,CONMEBOL,UEFA
2,WC-1970,1970 FIFA Men's World Cup,M-1970-03,England vs Romania,group stage,1970-06-02,T-28,England,T-61,Romania,...,0,0,0,0,home team win,1,0,0,UEFA,UEFA
3,WC-1970,1970 FIFA Men's World Cup,M-1970-04,Peru vs Bulgaria,group stage,1970-06-02,T-56,Peru,T-10,Bulgaria,...,0,0,0,0,home team win,1,0,0,CONMEBOL,UEFA
4,WC-1970,1970 FIFA Men's World Cup,M-1970-05,Belgium vs El Salvador,group stage,1970-06-03,T-06,Belgium,T-27,El Salvador,...,0,0,0,0,home team win,1,0,0,UEFA,CONCACAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
759,WC-2022,2022 FIFA Men's World Cup,M-2022-60,England vs France,quarter-finals,2022-12-10,T-28,England,T-30,France,...,0,0,0,0,away team win,0,1,0,UEFA,UEFA
760,WC-2022,2022 FIFA Men's World Cup,M-2022-61,Argentina vs Croatia,semi-finals,2022-12-13,T-03,Argentina,T-18,Croatia,...,0,0,0,0,home team win,1,0,0,CONMEBOL,UEFA
761,WC-2022,2022 FIFA Men's World Cup,M-2022-62,France vs Morocco,semi-finals,2022-12-14,T-30,France,T-47,Morocco,...,0,0,0,0,home team win,1,0,0,UEFA,CAF
762,WC-2022,2022 FIFA Men's World Cup,M-2022-63,Croatia vs Morocco,third-place match,2022-12-17,T-18,Croatia,T-47,Morocco,...,0,0,0,0,home team win,1,0,0,UEFA,CAF
763,WC-2022,2022 FIFA Men's World Cup,M-2022-64,Argentina vs France,final,2022-12-18,T-03,Argentina,T-30,France,...,1,1,4,2,home team win,1,0,0,CONMEBOL,UEFA